#!/usr/bin/env node

'use strict';

var aws = require('aws-sdk');
var HttpsProxyAgent = require('https-proxy-agent');
var argv = require('yargs').argv;
var Table = require('cli-table');
var fs = require('fs');
if(argv.hasOwnProperty('profile'))
	var profileToUse = argv.profile;
else
	var profileToUse = 'default';
var credentials = new aws.SharedIniFileCredentials({profile: profileToUse});
aws.config.credentials = credentials;

if (typeof process.env.https_proxy !== 'undefined') {
  aws.config.update({
    httpOptions: {
      agent: new HttpsProxyAgent(process.env.https_proxy)
    }
  });
}

if(argv.hasOwnProperty('region'))
	var regionToUse = argv.region;
else
	var regionToUse = 'ap-southeast-2';
var ec2 = new aws.EC2({region: regionToUse});



var constructed=[];
var table = new Table({
    head: ['','Name','ID','Type','LaunchedAt','IP','State']
  , colWidths: [5,40,12,12,28,20,20]
});
function usage()
{
	console.log("Usage");
	console.log("---------------------------------------------------------");
	console.log(process.argv[1] + " [--profile profileName] [--region awsRegion] arg1 [arg2]...[argN]");
	console.log("profileName: AWS profile to use, defaults to 'default' profile");
	console.log("awsRegion: AWS region to use, defaults to 'ap-southeast-2'");
	console.log("arg1: Search string in a dashed naming convention");
	console.log("argN: Search string in a dashed naming convention");
	console.log("For example , group-environment-*-application-single can be found with "+process.argv[1]+" group environment \"*\" application single");
}

if (process.argv.length < 4)
{
	usage();
	process.exit(1);
}

var finalString="";
var fileName = argv._[0];
for(var i=1; i< argv._.length; i++)
{
	if(finalString == "")
	{
		finalString = argv._[i];
	}
	else
	{
		finalString = finalString + "-" + argv._[i];
	}
}
finalString = finalString+"*"; 
var params = {
  DryRun: false,
  Filters : [
  	{
  		Name: 'tag:Name',
  		Values : [
  			finalString
  		]
  	}
  ]
};
ec2.describeInstances(params, function(err, data) {
  if (err) 
  	console.log(err, err.stack);
  else
  {
  		var counter = 0;
  		var constructCounter = 0;
  		if(data.Reservations.length > 0)
  		{
		  	for(var i=0;i<data.Reservations.length;i++)
		  	{
		  		for(var j=0; j<data.Reservations[i].Instances.length; j++)
		  		{
		  			for(var k=0;k<data.Reservations[i].Instances[j].Tags.length;k++)
			  		{
			  			if(data.Reservations[i].Instances[j].Tags[k].Key == "Name")
			  			{
			  				constructed[++constructCounter] = data.Reservations[i].Instances[j];
			  				if(typeof data.Reservations[i].Instances[j].PrivateIpAddress === 'undefined') {
			  					table.push([++counter,data.Reservations[i].Instances[j].Tags[k].Value,data.Reservations[i].Instances[j].InstanceId,data.Reservations[i].Instances[j].InstanceType,data.Reservations[i].Instances[j].LaunchTime,'n/a',data.Reservations[i].Instances[j].State.Name]);
			  				}
			  				else
			  				{
			  					table.push([++counter,data.Reservations[i].Instances[j].Tags[k].Value,data.Reservations[i].Instances[j].InstanceId,data.Reservations[i].Instances[j].InstanceType,data.Reservations[i].Instances[j].LaunchTime,data.Reservations[i].Instances[j].PrivateIpAddress,data.Reservations[i].Instances[j].State.Name]);	
			  				}
			  			}
			  			
			  		}	
		  		}
		  		
		  	}
		  	fs.writeFile(fileName, JSON.stringify(constructed), function (err) {
			  if (err) return console.log(err);
			  process.exit();
			});
		  	console.log(table.toString());
	  	}
	  	else
	  	{
	  		console.log("No instances found");
	  	}
  }
});
